/* Live Shift Command V10.1 — manager UI for process-run/hourly evidence */
(()=>{'use strict';
if(!document.getElementById('events'))return;
const C=window.LSC_V10_CORE;if(!C)return console.warn('[LSC V10 UI] core missing');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const current=()=>state?.current||null,areas=()=>state?.config?.areas||window.areas||[];
const round=(n,d=1)=>Number.isFinite(+n)?Math.round(+n*10**d)/10**d:null;
function evidence(rows){if(!rows.length)return'<div class="v10-empty">No captured evidence is attached to this run.</div>';return`<div class="v10-evidence">${rows.slice(-12).reverse().map(({e,t})=>`<div><b>${esc(String(e.type||'event').toUpperCase())} · ${esc(e.issueCode||e.category||'')}</b><span>${esc(e.reason||e.notes||'Captured record')}</span><small>${new Date(t).toLocaleString()} · ${esc(e.fourM||'4M not established')} · ${esc(e.originatingFunction||'origin not established')}</small></div>`).join('')}</div>`}
function hours(r){if(!r.hours.length)return'<div class="v10-empty">No process-attributed hourly production or event evidence is stored for this run yet.</div>';return`<div class="v10-hour-table"><div class="head"><b>Hour</b><b>Actual</b><b>Scrap / Rework</b><b>Downtime</b><b>Evidence</b><b>Top Code</b></div>${r.hours.map(h=>`<div><span>${esc(h.hour)}</span><span><b>${h.actualKnown?h.good:'—'}</b>${h.actualKnown?'':'<small>not attributed</small>'}</span><span>${h.scrap} / ${h.rework}</span><span>${round(h.downtime,1)||0}m</span><span>${h.events}</span><span>${esc(Object.entries(h.codes).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—')}</span></div>`).join('')}</div>`}
function runCard(r){return`<details class="v10-run" ${r.actualKnown||r.events.length?'open':''}><summary><div><small>${r.type==='process_schedule'?'PROCESS RUN':'PLANT PROCESS'}</small><b>${esc(r.name)}</b><span>${esc(r.area)} · ${esc(r.workDate||'')}</span></div><div><strong>${r.actualKnown?r.actualGood:'—'}</strong><small>PROCESS ACTUAL</small></div><div><strong>${r.downtime||0}m</strong><small>DOWNTIME</small></div><div><strong>${r.scrap} / ${r.rework}</strong><small>QUALITY</small></div></summary><div class="v10-run-body"><div class="v10-run-facts"><span><small>SCHEDULE</small><b>${r.start&&r.end?`${esc(r.start)} → ${esc(r.end)}`:'Plant-shift process context'}</b></span><span><small>TOP SIGNAL</small><b>${esc(r.topCode?`${r.topCode[0]} ×${r.topCode[1]}`:'No repeated code')}</b></span><span><small>4M BURDEN</small><b>${esc(r.topFourM?`${r.topFourM[0]} · ${round(r.topFourM[1],1)}m`:'No downtime 4M burden')}</b></span><span><small>PRODUCTION EVIDENCE</small><b>${r.processProduction.length?`${r.processProduction.length} process entry(s)`:'Actual not process-attributed'}</b></span></div>${hours(r)}<h4>Run Evidence</h4>${evidence(r.events)}</div></details>`}
function dayHtml(s){const shifts=s.shifts.map(x=>`<div><b>${esc(x.label||'Shift')}</b><span>${esc(x.workDate||'')}</span><strong>${x._actual.known?x._actual.good:'—'}</strong><small>${x._actual.known?'shift actual':'actual missing'}</small></div>`).join('');return`<div class="v10-day-head"><div><small>CALENDAR RECONSTRUCTION</small><h3>${esc(s.date)}</h3><p>Shift facts remain shift facts. Generic shift Actual is never redistributed across processes. Process Actual appears only when it was explicitly attributed.</p></div><div class="v10-day-kpis"><span><b>${s.shifts.length}</b><small>shifts</small></span><span><b>${s.events.length}</b><small>events</small></span><span><b>${s.downtime||0}m</b><small>downtime</small></span><span><b>${s.scrap} / ${s.rework}</b><small>scrap / rework</small></span></div></div><div class="v10-shift-strip">${shifts||'<div class="v10-empty">No shift records stored for this date.</div>'}</div><div class="v10-truth-note"><b>PRODUCTION TRUTH RULE</b><span>${s.processActualKnown?`${s.processActual} units are explicitly process-attributed on this date.`:'No process Actual is attributed yet. Missing data remains missing—not zero.'}</span></div><div class="v10-run-list">${s.runs.length?s.runs.map(runCard).join(''):'<div class="v10-empty">No configured or captured process run is available for this date.</div>'}</div>`}
async function openDay(date){const box=document.getElementById('v10DayBody');if(!box)return;box.innerHTML='<div class="v10-loading">Reconstructing calendar evidence…</div>';const s=await C.daySnapshot(date);box.innerHTML=dayHtml(s);window.LSC_V10_LAST_DAY=s;return s}
function installCalendar(){if(document.getElementById('v10Calendar'))return;const a=document.getElementById('v9MemoryBrowser')||document.querySelector('.mi-section')||[...document.querySelectorAll('.section')].find(x=>x.querySelector('h2')?.textContent==='Event Timeline');if(!a)return;a.insertAdjacentHTML('afterend',`<section class="section v10-calendar" id="v10Calendar"><div class="v10-heading"><div><div class="v10-eyebrow">V10 · CALENDAR-FIRST EVIDENCE</div><h2>Day Reconstruction · Process Runs</h2></div><span>Shift → process run → hour → evidence</span></div><div class="v10-controls"><button data-v10="today">TODAY</button><button data-v10="yesterday">YESTERDAY</button><input id="v10Date" type="date" value="${C.parts().date}"><button id="v10Open">OPEN DATE</button></div><div id="v10DayBody" class="v10-empty">Choose a date to reconstruct the plant record.</div></section>`);document.querySelector('[data-v10="today"]').onclick=()=>{const d=C.parts().date;document.getElementById('v10Date').value=d;openDay(d)};document.querySelector('[data-v10="yesterday"]').onclick=()=>{const d=C.addDate(C.parts().date,-1);document.getElementById('v10Date').value=d;openDay(d)};document.getElementById('v10Open').onclick=()=>openDay(document.getElementById('v10Date').value)}
function liveRows(){const now=Date.now();return areas().map(area=>{const r=C.runIdentity(area,now),p=(current()?.processProduction||[]).filter(x=>x.runInstanceId===r.id).sort((a,b)=>+new Date(b.timestamp)-+new Date(a.timestamp))[0],open=(current()?.events||[]).filter(e=>e.type==='downtime'&&!e.endedAt&&(e.affectedProcess||e.area)===area).length,q=(current()?.events||[]).filter(e=>['scrap','rework'].includes(e.type)&&(e.processArea||e.area)===area).reduce((n,e)=>n+(+e.quantity||0),0);return{...r,last:p,open,q}})}
function liveHtml(){return`<div class="v10-live-strip"><div class="v10-live-title"><div><small>PROCESS RUN CONTEXT · V10</small><b>Current area/run evidence</b></div><button id="v10ProcessActual">＋ PROCESS ACTUAL</button></div><div class="v10-live-grid">${liveRows().map(r=>`<div><b>${esc(r.area)}</b><span>${esc(r.name)}</span><small>${r.open?`${r.open} active stop(s)`:r.q?`${r.q} quality piece(s)`:'No active captured loss'} · Actual ${C.goodVal(r.last?.good)??'not attributed'}</small></div>`).join('')}</div></div>`}
function installLive(){const h=document.getElementById('v9LiveBody');if(!h||document.getElementById('v10LiveStrip'))return;h.insertAdjacentHTML('beforeend',`<div id="v10LiveStrip">${liveHtml()}</div>`);wireLive()}
function wireLive(){const b=document.getElementById('v10ProcessActual');if(b)b.onclick=openActual}
function refreshLive(){const h=document.getElementById('v10LiveStrip');if(!h)return installLive();h.innerHTML=liveHtml();wireLive()}
function form(){const p=C.parts();return`<div class="v10-form"><p class="v10-help">Supplemental process-level Good Actual only. This never replaces shift Actual. Scrap and Rework stay in the existing quality workflow so they are counted once.</p><label>Process / area<select id="v10PaArea">${areas().map(a=>`<option>${esc(a)}</option>`).join('')}</select></label><label>Good actual<input id="v10PaGood" type="number" min="0" inputmode="numeric" placeholder="Good pieces"></label><label>Plant hour · Chicago<input id="v10PaHour" type="datetime-local" value="${p.date}T${String(p.hour).padStart(2,'0')}:00"></label><label>Evidence note<textarea id="v10PaNote" placeholder="Optional: MES reading, source, run note"></textarea></label><button class="v10-primary" id="v10PaSave">SAVE PROCESS ACTUAL</button></div>`}
function openActual(){if(!current())return;const showFn=window.show||show;showFn('Process Actual · V10',form(),'PROCESS RUN · HOURLY EVIDENCE');document.getElementById('v10PaSave').onclick=saveActual}
async function saveActual(){const area=document.getElementById('v10PaArea').value,raw=document.getElementById('v10PaGood').value,note=document.getElementById('v10PaNote').value.trim();if(raw==='')return alert('Enter Good Actual for this process hour.');await C.recordProcessActual({area,good:+raw,timestamp:C.plantLocalEpoch(document.getElementById('v10PaHour').value),note,source:'manager_manual_process_actual'});try{modal.close()}catch{}refreshLive();const d=document.getElementById('v10Date')?.value;if(d)openDay(d)}
window.LSC_V10_OPEN_DAY=openDay;
installCalendar();installLive();setTimeout(()=>openDay(C.parts().date),120);setInterval(refreshLive,5000);
console.info('[LSC] V10.1 UI active · process Actual isolated from shift Actual and quality');
})();